[env:unix]
board = megaatmega2560
platform = atmelavr
framework = arduino
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
monitor_speed = 115200
check_tool =
    cppcheck
    clangtidy
check_flags = cpp_check: --enable=all --inline-suppr
check_skip_packages = yes
check_severity =
    high
    medium
    low
